yum_repos:
  docker-ce-stable:
    name: docker-ce-stable
    description: Docker-CE repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
    repo_gpgcheck: 1
  google-chrome:
    name: google-chrome
    description: Google chrome repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    repo_gpgcheck: 1
  microsoft:
    name: microsoft
    description: Microsoft repository
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: 1
  virtualbox:
    name: virtualbox
    description: Virtualbox repository
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    repo_gpgcheck: 1
  vscode:
    name: vscode
    description: Visual Studio Code repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    repo_gpgcheck: 1

flatpak_repos:
  flathub:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

pre_req_yum_packages:
- binutils
- dkms
- dnf-plugins-core
- fontforge
- gcc
- glibc-devel
- glibc-headers
- gnome-tweak-tool
- icedtea-web
- java-1.8.0-openjdk
- jq
- kernel-devel
- kernel-headers
- krb5-devel
- krb5-workstation
- libffi-devel
- libgomp
- libselinux-python3
- make
- net-tools
- openssl-devel
- patch
- python3-devel
- python3-dnf
- qt
- redhat-rpm-config
- ruby
- rubygems
- xsel
- zypper

yum_packages:
- '@kde-desktop'
- code
- docker-ce
- git
- gimp
- gnome-screensaver
- gnome-tweak-tool
- google-chrome-stable
- kleopatra
- libreoffice-base
- openvpn
- powershell
- remmina
- seahorse
- switchdesk-gui
- tigervnc
- tmux
- VirtualBox-6.0
- xfreerdp

flatpaks:
  pycharm:
    name: com.jetbrains.PyCharm-Community
    remote: flathub

ruby_gems:
- hiera-eyaml
- rake

vagrant_version: 2.0.0

managed_services:
- docker
- firewalld
- fstrim.timer
