repos:
  docker-ce-stable:
    name: docker-ce-stable
    description: Docker-CE repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
    repo_gpgcheck: 1
  google-chrome:
    name: google-chrome
    description: Google chrome repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    repo_gpgcheck: 1
  virtualbox:
    name: virtualbox
    description: Virtualbox repository
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    repo_gpgcheck: 1

pre_req_packages:
- binutils
- dkms
- dnf-plugins-core
- fontforge
- gcc
- glibc-devel
- glibc-headers
- gnome-tweak-tool
- icedtea-web
- java-1.8.0-openjdk
- kernel-devel
- kernel-headers
- libgomp
- libselinux-python
- make
- net-tools
- patch
- python-dnf
- qt
- ruby
- rubygems
- zypper

main_packages:
- '@kde-desktop'
- ansible
- docker-ce
- gnome-screensaver
- gnome-tweak-tool
- google-chrome-stable
- git
- libreoffice-base
- switchdesk-gui
- tigervnc
- tmux
- VirtualBox-5.1
- xfreerdp

ruby_gems:
- hiera-eyaml
- rake

vagrant_version: 2.0.0

managed_services:
- docker
- firewalld
- fstrim.timer


