- name: retrieve the kernel version
  command: uname -r
  register: cur_kernel_version 
  changed_when: cur_kernel_version != cur_kernel_version
- name: ensure environment variables exist
  lineinfile:
    path: ~/.bashrc
    line: KERN_DIR=/usr/src/kernels/{{ cur_kernel_version.stdout }}
    state: present
- name: verify kern_dir is set
  command: echo $KERN_DIR
  register: kern_dir_status
- name: restart if kern_dir is not valid
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  when: (kern_dir_status.stdout != cur_kernel_version.stdout)
- name: Wait for server come back
  wait_for: >
       host={{ inventory_hostname }}
       port=22
       delay=15
       timeout=600
  delegate_to: localhost
- name: debug line
  debug: 
    msg: "{{ kern_dir_status }}" 
# - name: restart if kern_dir not set  
- name: install pre-requisite packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ pre_req_packages }}"
- name: add google-chrome repository
  yum_repository:
    name: google-chrome
    description: Google chrome repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
- name: add virtualbox repository
  yum_repository:
    name: virtualbox
    description: Virtualbox repository
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    repo_gpgcheck: 1
- name: install apps
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ dnf_packages }}"
