- name: install pre-requisite packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ pre_req_packages }}"
- name: add google-chrome repository
  yum_repository:
    name: google-chrome
    description: Google chrome repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
- name: add virtualbox repository
  yum_repository:
    name: virtualbox
    description: Virtualbox repository
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    repo_gpgcheck: 1
- name: install apps via yum repos
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ dnf_packages }}"
- name: check for vagrant
  command: ls /opt/
  register: status_vagrant
  changed_when: status_vagrant != status_vagrant
- name: download vagrant
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
    dest: "/tmp/vagrant_{{ vagrant_version }}_x86_64.rpm"
    force: yes  
  when: "'vagrant' not in status_vagrant.stdout_lines"
- name: verify vagrant rpm
  stat:
    path: "/tmp/vagrant_{{ vagrant_version }}_x86_64.rpm"
  when: "'vagrant' not in status_vagrant.stdout_lines"
  register: status_vagrant_rpm
- name: install vagrant
  dnf:
    name: "/tmp/vagrant_{{ vagrant_version }}_x86_64.rpm"
    state: present
  when:
  - "'vagrant' not in status_vagrant.stdout_lines"
  - status_vagrant_rpm is defined
- name: cleanup vagrant rpm
  file:
    path: "/tmp/vagrant_{{ vagrant_version }}_x86_64.rpm"
    state: absent
- name: install ruby gems
  gem:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ ruby_gems }}"
