- name: ensure yum repositories exist
  yum_repository:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    baseurl: "{{ item.value.baseurl }}"
    enabled: "{{ item.value.enabled }}"
    gpgcheck: "{{ item.value.gpgcheck }}"
    gpgkey: "{{ item.value.gpgkey }}"
    repo_gpgcheck: "{{ item.value.repo_gpgcheck }}"
  with_dict: "{{ yum_repos }}"
  become: yes

- name: ensure flatpak repositories exist
  flatpak_remote:
    name: "{{ item.value.name }}"
    state: present
    flatpakrepo_url: "{{ item.value.flatpakrepo_url }}"
    method: "{{ item.value.method }}"
  with_dict: "{{ flatpak_repos }}"
  become: yes

- name: ensure pre-requisites installed
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ pre_req_yum_packages }}"
  become: yes

- name: ensure apps installed
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ yum_packages }}"
  become: yes

- name: ensure flatpaks installed
  flatpak:
    name: "{{ item.value.name }}"
    repo: "{{ item.value.remote }}"
    state: present
  with_dict: "{{ flatpaks }}"

- name: ensure ruby gems installed
  gem:
    name: "{{ item }}"
    state: present
  loop: "{{ ruby_gems }}"

- name: ensure service state
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ managed_services }}"
  become: yes
